package fitnessApp;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * This class will create a JFrame that will display the menu to the member
 * @author Adrian Foo
 */
public class MemberMenu extends javax.swing.JFrame {
    private Frame mainMenuFrame;
    private Member theMember;
    private HELPFit HF;
    int xMouse;
    int yMouse;
    /**
     * This is the constructor that create the window to display the menu to 
     * the member
     */
    public MemberMenu(Frame mainMenuFrame, Member theMember) {
        initComponents();
        this.mainMenuFrame = mainMenuFrame;
        this.theMember = theMember;
        userNameLabel.setText(theMember.getFullName());
        HF = ((HFGUI)mainMenuFrame).getHF();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-
                this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sessionHistoryBtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        updateProfileBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registerSessionBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();
        reviewSesionBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 49, 67));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 49, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setBackground(new java.awt.Color(83, 197, 185));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Export_48px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        sessionHistoryBtn.setBackground(new java.awt.Color(83, 197, 185));
        sessionHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sessionHistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sessionHistoryBtnMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/List View_48px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Session History");

        javax.swing.GroupLayout sessionHistoryBtnLayout = new javax.swing.GroupLayout(sessionHistoryBtn);
        sessionHistoryBtn.setLayout(sessionHistoryBtnLayout);
        sessionHistoryBtnLayout.setHorizontalGroup(
            sessionHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionHistoryBtnLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sessionHistoryBtnLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(21, 21, 21))
        );
        sessionHistoryBtnLayout.setVerticalGroup(
            sessionHistoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionHistoryBtnLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel1.add(sessionHistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        updateProfileBtn.setBackground(new java.awt.Color(83, 197, 185));
        updateProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Registration_48px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Profile");

        javax.swing.GroupLayout updateProfileBtnLayout = new javax.swing.GroupLayout(updateProfileBtn);
        updateProfileBtn.setLayout(updateProfileBtnLayout);
        updateProfileBtnLayout.setHorizontalGroup(
            updateProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfileBtnLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(updateProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProfileBtnLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProfileBtnLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42))))
        );
        updateProfileBtnLayout.setVerticalGroup(
            updateProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfileBtnLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(updateProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 140, 140));

        registerSessionBtn.setBackground(new java.awt.Color(83, 197, 185));
        registerSessionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerSessionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerSessionBtnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Register Session");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Add Property_48px.png"))); // NOI18N

        javax.swing.GroupLayout registerSessionBtnLayout = new javax.swing.GroupLayout(registerSessionBtn);
        registerSessionBtn.setLayout(registerSessionBtnLayout);
        registerSessionBtnLayout.setHorizontalGroup(
            registerSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerSessionBtnLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(registerSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerSessionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerSessionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(19, 19, 19))))
        );
        registerSessionBtnLayout.setVerticalGroup(
            registerSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerSessionBtnLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(28, 28, 28))
        );

        jPanel1.add(registerSessionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("HELP Fit");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("userName");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Minus_24px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/User_24px.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Delete_24px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        jPanel1.add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 670, 40));

        reviewSesionBtn.setBackground(new java.awt.Color(83, 197, 185));
        reviewSesionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reviewSesionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewSesionBtnMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Comments_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Review Session");

        javax.swing.GroupLayout reviewSesionBtnLayout = new javax.swing.GroupLayout(reviewSesionBtn);
        reviewSesionBtn.setLayout(reviewSesionBtnLayout);
        reviewSesionBtnLayout.setHorizontalGroup(
            reviewSesionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewSesionBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reviewSesionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reviewSesionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reviewSesionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(46, 46, 46))))
        );
        reviewSesionBtnLayout.setVerticalGroup(
            reviewSesionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reviewSesionBtnLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(reviewSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 140, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This function will minimize the window when the minimize label
     * is clicked
     * @param evt 
     */
    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked
    /**
     * This function will exit the program when the close label 
     * is clicked
     * @param evt 
     */
    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged
    /**
     * This function will allow the user to drag the dragFrame when the user
     * dragging the frame
     * @param evt 
     */
    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed
    /**
     * This function will display the "update profile dialog" to the member
     * when the update profile button is clicked
     * @param evt 
     */
    private void updateProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseClicked
        editProfileMemberDialog epmd = new editProfileMemberDialog(
        this, true, theMember);
        epmd.setVisible(true);
        userNameLabel.setText(theMember.getFullName());
    }//GEN-LAST:event_updateProfileBtnMouseClicked
    /**
     * This function will display the "session available window" when the 
     * user clicked on the register session button
     * @param evt 
     */
    private void registerSessionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerSessionBtnMouseClicked
        SessionAvailableWindow saw = new SessionAvailableWindow(HF, theMember);
        saw.setVisible(true);
    }//GEN-LAST:event_registerSessionBtnMouseClicked
    /**
     * This function will display the trainig session history that the
     * member has registered
     * @param evt 
     */
    private void sessionHistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sessionHistoryBtnMouseClicked
        TrainingHistoryWindow thw = new TrainingHistoryWindow(theMember);
        thw.setVisible(true);
    }//GEN-LAST:event_sessionHistoryBtnMouseClicked
    /**
     * This function will allow the member to review a trainer from a 
     * training session if the user has registered for a training session
     * by displaying the "review trainer frame" when the review session
     * button is clicked
     * @param evt 
     */
    private void reviewSesionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewSesionBtnMouseClicked
        int length = theMember.getTrainingSessions().size();
        String[] list = new String[length];
        String[] options = {"OK"};
        int i = 0;
        for (TrainingSession ts: theMember.getTrainingSessions()){
            list[i] = ts.getSessionID();
            i++;
        }
        if(length == 0){
            JOptionPane.showOptionDialog(this, "You haven't register for "
                    + "any training session yet! ",
                "", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0] );
        }
        else{
            String sessionID = (String)
            JOptionPane.showInputDialog(this, "Please select a session ID", 
                "", JOptionPane.QUESTION_MESSAGE, null, list, list[0]);
            TrainingSession theSession = theMember.findSession(sessionID);
            if(theSession instanceof GroupTraining){
                ReviewTrainerG_Dialog rtpd = new ReviewTrainerG_Dialog(this, 
                        true, theMember, (GroupTraining)theSession);
                rtpd.setVisible(true);
            }
            else if(theSession instanceof PersonalTraining){
                ReviewTrainerP_Dialog rtpd = new ReviewTrainerP_Dialog(this, 
                        true, (PersonalTraining)theSession, theMember);
                rtpd.setVisible(true);
            }
        }
    }//GEN-LAST:event_reviewSesionBtnMouseClicked
    /**
     * This function will close the menu frame and proceed back to HFGUI
     * @param evt 
     */
    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.setVisible(false);
        mainMenuFrame.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel registerSessionBtn;
    private javax.swing.JPanel reviewSesionBtn;
    private javax.swing.JPanel sessionHistoryBtn;
    private javax.swing.JPanel updateProfileBtn;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
