package fitnessApp;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 * This is a class that will create a form for the trainer to create a
 * new personal training session
 * @author foo
 */
public class NewPersonalTrainingSession extends javax.swing.JDialog {
    private Trainer theTrainer;
    private HELPFit HF;
    int xMouse;
        int yMouse;
    /**
     * This is the constructor to create the form for trainer to 
     * create new personal training session
     */
    public NewPersonalTrainingSession(java.awt.Frame parent, boolean modal, 
            Trainer theTrainer) {
        super(parent, modal);
        initComponents();
        this.theTrainer = theTrainer;
        HF = ((HFGUI)parent).getHF();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        feeTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 49, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Title: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fee: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        titleTF.setBackground(new java.awt.Color(36, 49, 67));
        titleTF.setForeground(new java.awt.Color(255, 255, 255));
        titleTF.setBorder(null);
        titleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTFActionPerformed(evt);
            }
        });
        jPanel1.add(titleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 325, 38));

        dateTF.setBackground(new java.awt.Color(36, 49, 67));
        dateTF.setForeground(new java.awt.Color(255, 255, 255));
        dateTF.setBorder(null);
        jPanel1.add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 325, 38));

        feeTF.setBackground(new java.awt.Color(36, 49, 67));
        feeTF.setForeground(new java.awt.Color(255, 255, 255));
        feeTF.setBorder(null);
        jPanel1.add(feeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 325, 38));

        timeTF.setBackground(new java.awt.Color(36, 49, 67));
        timeTF.setForeground(new java.awt.Color(255, 255, 255));
        timeTF.setBorder(null);
        jPanel1.add(timeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 325, 38));

        createBtn.setBackground(new java.awt.Color(83, 197, 185));
        createBtn.setText("Create");
        createBtn.setBorder(null);
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 102, 49));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 330, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 320, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 320, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 450, 510));

        jPanel2.setBackground(new java.awt.Color(83, 197, 185));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Personal Training");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/User_96px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Delete_24px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        jPanel2.add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTFActionPerformed
    /**
     * This function will create the new personal training session when the 
     * create button is clicked by using the HELPFit controller if all the 
     * information entered is valid
     * @param evt 
     */
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        PersonalTraining theSession = null;
        String[] options = {"OK"};
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("d/M/y");
        DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern("h:m a");
        String title = titleTF.getText();
        LocalDate sessionDate = null;
        LocalTime sessionTime = null;
        boolean validDate = false;
        boolean validTime = false;
        boolean validFee = false;
        double fee = 0;
        
        if (title.equals("") || dateTF.equals("") || timeTF.getText().equals("") ||
                feeTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill in the details required!");
            
        }
        else {
            try {
                String date = dateTF.getText();
                sessionDate = LocalDate.parse(date, dateFormat);
                if (sessionDate.isBefore(LocalDate.now())) {
                    JOptionPane.showMessageDialog(this, "Session date cannot "
                            + "be before today!");
                }
                else {
                    validDate = true;
                }

            } catch (DateTimeParseException dtpe) {
                JOptionPane.showMessageDialog(this, "Invalid date entered, "
                        + "please re-enter date as dd/mm/yyy");
            }
            
            try {
                String time = timeTF.getText().toUpperCase();
                sessionTime = LocalTime.parse(time, timeFormat);
                validTime = true;
            } catch (DateTimeParseException dtpe) {
                JOptionPane.showMessageDialog(this, "Invalid time entered, "
                        + "please re-enter time as HH:MM AM/PM");
            }
            
            try {
                fee = Double.parseDouble(feeTF.getText());
                if (fee > 0) {
                    validFee = true;
                }
                else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid "
                            + "number, for the fee!");
                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Please enter a number, "
                        + "for the fee!");
            }
            
            if (validDate && validTime && validFee) {
                theSession = theTrainer.addPersonalTraining(title, sessionDate, 
                        sessionTime, fee);
                if (theSession != null){
                    HF.addTrainingSession(theSession); 
                    JOptionPane.showOptionDialog(this, "Session Created! ", 
                            "", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE,
                            null, options, options[0] );
                    this.dispose();
                }
                else{
                    JOptionPane.showOptionDialog(this, "Session Not Created! ", 
                            "", JOptionPane.OK_OPTION, JOptionPane.ERROR,
                            null, options, options[0] );
                }
            }
        }   
    }//GEN-LAST:event_createBtnActionPerformed
    /**
     * This function will close the window when the close label 
     * is clicked
     * @param evt 
     */
    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked
    /**
     * This function will allow the user to drag the dragFrame when the user
     * dragging the frame
     * @param evt 
     */
    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged
    /**
     * This function will get the location of the mouse when the user 
     * click on the dragFrame
     * @param evt 
     */
    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField feeTF;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
