package fitnessApp;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * This class will create a JFrame that will display the menu to the trainer
 * @author Adrian Foo
 */
public class TrainerMenu extends javax.swing.JFrame {
    private Frame mainMenuFrame;
    private Trainer theTrainer;
    int xMouse;
    int yMouse;
    /**
     * This is the constructor to create the frame that display all the
     * option to the trainer
     */
    public TrainerMenu(Frame mainMenuFrame, Trainer theTrainer) {
        initComponents();
        this.mainMenuFrame = mainMenuFrame;
        this.theTrainer = theTrainer;
        userNameLabel.setText(theTrainer.getFullName());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        updateProfileBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newSessionBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updateSessionBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sessionHisotryBtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 49, 67));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 49, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("HELP Fit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        updateProfileBtn.setBackground(new java.awt.Color(83, 197, 185));
        updateProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Registration_48px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Profile");

        javax.swing.GroupLayout updateProfileBtnLayout = new javax.swing.GroupLayout(updateProfileBtn);
        updateProfileBtn.setLayout(updateProfileBtnLayout);
        updateProfileBtnLayout.setHorizontalGroup(
            updateProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfileBtnLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProfileBtnLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(26, 26, 26))
        );
        updateProfileBtnLayout.setVerticalGroup(
            updateProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfileBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(updateProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(236, 240, 241));
        userNameLabel.setText("userName");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/User_24px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        newSessionBtn.setBackground(new java.awt.Color(83, 197, 185));
        newSessionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newSessionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newSessionBtnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("New Session");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Add Property_48px.png"))); // NOI18N

        javax.swing.GroupLayout newSessionBtnLayout = new javax.swing.GroupLayout(newSessionBtn);
        newSessionBtn.setLayout(newSessionBtnLayout);
        newSessionBtnLayout.setHorizontalGroup(
            newSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSessionBtnLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(newSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newSessionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newSessionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        newSessionBtnLayout.setVerticalGroup(
            newSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newSessionBtnLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(28, 28, 28))
        );

        jPanel1.add(newSessionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 139));

        updateSessionBtn.setBackground(new java.awt.Color(83, 197, 185));
        updateSessionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateSessionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateSessionBtnMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Edit Property_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Update Session");

        javax.swing.GroupLayout updateSessionBtnLayout = new javax.swing.GroupLayout(updateSessionBtn);
        updateSessionBtn.setLayout(updateSessionBtnLayout);
        updateSessionBtnLayout.setHorizontalGroup(
            updateSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateSessionBtnLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(updateSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateSessionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateSessionBtnLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(46, 46, 46))))
        );
        updateSessionBtnLayout.setVerticalGroup(
            updateSessionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateSessionBtnLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(updateSessionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        logoutBtn.setBackground(new java.awt.Color(83, 197, 185));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Export_48px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        sessionHisotryBtn.setBackground(new java.awt.Color(83, 197, 185));
        sessionHisotryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sessionHisotryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sessionHisotryBtnMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/List View_48px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Session History");

        javax.swing.GroupLayout sessionHisotryBtnLayout = new javax.swing.GroupLayout(sessionHisotryBtn);
        sessionHisotryBtn.setLayout(sessionHisotryBtnLayout);
        sessionHisotryBtnLayout.setHorizontalGroup(
            sessionHisotryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionHisotryBtnLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sessionHisotryBtnLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(21, 21, 21))
        );
        sessionHisotryBtnLayout.setVerticalGroup(
            sessionHisotryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionHisotryBtnLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel1.add(sessionHisotryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Minus_24px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessApp/img/Delete_24px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        jPanel1.add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked
    /**
     * This function will exit the program when the close label 
     * is clicked
     * @param evt 
     */
    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked
    /**
     * This function will check whether the trainer has created any
     * training session and will allow the trainer to update the 
     * training session if a session is selected by displaying 
     * the "update session dialog" when the update session button is
     * clicked
     * @param evt 
     */
    private void updateSessionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSessionBtnMouseClicked
        int length = theTrainer.getTrainingSessions().size();
        String[] list = new String[length];
        String[] options = {"OK"};
        int i = 0;
        for (TrainingSession ts: theTrainer.getTrainingSessions()){
            list[i] = ts.getSessionID();
            i++;
        }
        if(length == 0){
            JOptionPane.showOptionDialog(this, "You haven't create "
                    + "any training session yet! ",
                "", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0] );
        }
        else{
            String sessionID = (String)
            JOptionPane.showInputDialog(this, "Please select a session ID", 
                "", JOptionPane.QUESTION_MESSAGE, null, list, list[0]);
            TrainingSession theSession = theTrainer.findSession(sessionID);
            if(theSession instanceof GroupTraining){
                this.setVisible(false);
                UpdateGroupSessionWindow ugsw = new UpdateGroupSessionWindow(
                this, (GroupTraining)theSession);
                ugsw.setVisible(true);
            }
            else if(theSession instanceof PersonalTraining){
                this.setVisible(false);
                UpdatePersonalSessionWindow upsw = new UpdatePersonalSessionWindow(
                this, (PersonalTraining)theSession);
                upsw.setVisible(true);
            }
        }
    }//GEN-LAST:event_updateSessionBtnMouseClicked
    /**
     * This function will ask the trainer whether he/she want to create
     * a group training session or personal training session and will display
     * the respective "create session dialog" when teh new session button 
     * is clicked
     * @param evt 
     */
    private void newSessionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSessionBtnMouseClicked
        String[] options = {
            "Group Session", "Personal Training"
        };
        int opt = JOptionPane.showOptionDialog(this, 
                "Which type of training session you want to add? ", 
                "",
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.QUESTION_MESSAGE,
                null, 
                options, 
                options[1]);
        
       if(opt == 1){
           NewPersonalTrainingSession ps = new NewPersonalTrainingSession(mainMenuFrame, true, 
           theTrainer);
           ps.setVisible(true);
       }
       else if(opt == 0){
           NewGroupTrainingSession ps = new NewGroupTrainingSession(mainMenuFrame, true, 
           theTrainer);
           ps.setVisible(true);
       }
    }//GEN-LAST:event_newSessionBtnMouseClicked
    /**
     * This function will display the "update profile dialog" to the trainer
     * when the update profile button is clicked
     * @param evt 
     */
    private void updateProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseClicked
        editProfileTrainerDialog epmd = new editProfileTrainerDialog(
        this, true, theTrainer);
        epmd.setVisible(true);
        userNameLabel.setText(theTrainer.getFullName());
    }//GEN-LAST:event_updateProfileBtnMouseClicked
    /**
     * This function will close the menu frame and proceed back to HFGUI
     * @param evt 
     */
    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.setVisible(false);
        mainMenuFrame.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked
    /**
     * This function will allow the user to drag the dragFrame when the user
     * dragging the frame
     * @param evt 
     */
    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged
    /**
     * This function will get the location of the mouse when the user 
     * click on the dragFrame
     * @param evt 
     */
    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed
    /**
     * This function will display the trainig session history that the
     * trainer has created
     * @param evt 
     */
    private void sessionHisotryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sessionHisotryBtnMouseClicked
        TrainingHistoryWindow thw = new TrainingHistoryWindow(theTrainer);
        thw.setVisible(true);
    }//GEN-LAST:event_sessionHisotryBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel newSessionBtn;
    private javax.swing.JPanel sessionHisotryBtn;
    private javax.swing.JPanel updateProfileBtn;
    private javax.swing.JPanel updateSessionBtn;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
